### ISSUE TITLE
Extend CakePHP's Helpers?

### ISSUE THREAD

**Issue by sime** [loadsys/twitter-bootstrap-helper#13]
Hi,

It kind of feels like this plugin is going in the wrong direction. Wouldn't it be better to extend the Helper's (say Form)? So one can use the standard CakePHP syntax: <code>$this->Form->input();</code>

Example how this would be instantiated:
https://github.com/CakePHP-Courses/Taking-Control/blob/master/app/Controller/AppController.php#L5

Basic structure  of the helper (note the parent::input call):
https://github.com/CakePHP-Courses/Taking-Control/blob/master/app/View/Helper/BootstrapFormHelper.php#L12

**Comment by joeytrapp** [comment]
I personally don't like overwriting the core helpers using the aliases with helpers that radically change or add functionality. It can obscure what is happening in the application. That was my reasoning for making it all in one helper. Also it started small and quickly had all the features added.

I do like the idea of breaking up the pieces of the helper into different helpers so that others could alias them over the core helpers. This would definitely be something to consider after all the pieces have been stabilized and are fully tested. I know of a few things left dealing with inputs that need to be fixed.

**Comment by jeremyharris** [comment]
I agree that this should extend the form helper. Not only does this benefit using it as an alias if you wanted to, it will help ensure all `FormHelper::input()` keys are accepted and that there are less discrepancies so devs won't have to think about it. For example, things like primary key's becoming hidden fields is done in the FormHelper but not here, so I would a) have to think about it, and b) have to use two different helpers to resolve it.

**Comment by joeytrapp** [comment]
Checkout the 2.1 branch. I've moved all the existing code over to 3 new helpers and ported all the unit tests. Now to refactor and add new functionality to the BootstrapFormHelper.

Going to close this issue. Please add more for other features you'd like to see in the BootstrapHelper, BootstrapFormHelper, and BootstrapHtmlHelper.

**Comment by rchavik** [comment]
@joeytrapp 

Thanks for separating them into different helpers and extending the appropriate Helper.

I have just tried plugging this in to replace FormHelper in Croogo and in a glance, it works out of the box.  Nice!

:+1::+1::+1:

**Comment by joeytrapp** [comment]
There is still a lot of work to be done to fully extend the form helper. I'll probably start new branches for this as it may break backwards compatibility.
